services:
    mega_data.transport:
        class: GuzzleHttp\Client
        arguments:
            -
                connect_timeout: 2
                timeout: 10
                allow_redirects: true